### ISSUE TITLE
Dataset can't infer data shape

### ISSUE THREAD

**Issue by scamalan** [catarina-barata/skin-hierarchy#3]
I was trying to run this code, but it was not able to properly use the dataset. When I ran it, I got the error below. When we query the shape of the dataset after loading it in, it gives ? for the first dimension. Was there more data we were not aware of or is there an issue with our formatting? We used TF 1.13.1, Python 3.6.13, and Numpy 1.19.2

`Traceback (most recent call last):
  File "hierarchical_attention_train.py", line 583, in <module>
    tf.app.run(main=main)
  File "..../skin-env/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "hierarchical_attention_train.py", line 321, in main
    maxlen,n_words,vocab,word_embedding,Flags.class_inf,Flags.net)
  File "hierarchical_attention_train.py", line 84, in apply_lstm
    image_embedding,att_weights = att.attention(data,state,int(data.shape[2]),Flags.ratio,1)
  File ".../skin-hierarchy/attention_modules.py", line 22, in attention
    data_ch = tf.reshape(data,[int(data.shape[0]),9,9,int(data.shape[2])])
TypeError: __int__ returned non-int (type NoneType)`

**Comment by catarina-barata** [comment]
Sorry for delay - out of the office.

Please use the updated versions of the attention_modules.py and hierarchical_attention_train.py files
